package swing.forms;

import taskjournal.TaskListImpl;
import taskjournal.task.Task;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;

/**
 * Created by Рената on 04.12.2016.
 */
public class PostponeForm extends JFrame {
    private JTextArea dataTextArea;
    private JTextPane dateTextPane;
    private JButton changeButton;
    private JPanel mainPanel;
    private Task task;

    public PostponeForm(Task task) throws HeadlessException {

        $$$setupUI$$$();
        setTitle("change date");
        getContentPane().add($$$getRootComponent$$$());
        pack();
        setVisible(true);
        setLocationRelativeTo(null);
        this.task = task;
        changeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                changeTask();
            }
        });
    }

    private void changeTask() {

        GregorianCalendar dueDate = new GregorianCalendar();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy/HH/mm");
        try {
            dueDate.setTimeInMillis(formatter.parse(dataTextArea.getText()).getTime());
            dataTextArea.setBackground(Color.WHITE);
            if (TaskListImpl.getTaskListImpl().getTask(task) == null) {
                return;
            } else {
                TaskListImpl.getTaskListImpl().getTask(task).setDueDate(dueDate);
            }
            this.dispose();

        } catch (ParseException e) {
            dataTextArea.setBackground(Color.PINK);
            e.printStackTrace();
        }

    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setMinimumSize(new Dimension(158, 200));
        mainPanel.setPreferredSize(new Dimension(405, 200));
        dataTextArea = new JTextArea();
        dataTextArea.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(dataTextArea, gbc);
        changeButton = new JButton();
        changeButton.setEnabled(true);
        changeButton.setText("Change");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(changeButton, gbc);
        dateTextPane = new JTextPane();
        dateTextPane.setEditable(false);
        dateTextPane.setText("Введите новую дату в формате dd/mm/yyyy/hh/mm");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(dateTextPane, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
